{"time":"2025-05-06T16:45:00.285022151+08:00","level":"INFO","msg":"stream: starting","core version":"0.19.9","symlink path":"/workspace/hide_lyf/DPOjudge/wandb/run-20250506_164500-9xovxj44/logs/debug-core.log"}
{"time":"2025-05-06T16:45:00.65131122+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:45:02.992686223+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:45:07.224814712+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:45:15.683552256+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:45:38.444255811+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:46:17.156483448+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:47:17.185956451+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:48:22.232532945+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:49:22.262108994+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:50:22.325479504+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:51:22.355177853+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:52:28.41458254+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:53:28.463473838+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:54:28.668687811+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:55:28.730373423+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:56:28.760192374+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:57:28.789223798+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:58:28.8186133+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T16:59:28.847267101+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:00:28.876643198+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:01:28.933726151+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:01:28.933913156+08:00","level":"ERROR","msg":"Failed to load features, feature will default to disabled","error":"api: failed sending: POST https://api.wandb.ai/graphql giving up after 21 attempt(s): Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:01:28.934231807+08:00","level":"INFO","msg":"created new stream","id":"9xovxj44"}
{"time":"2025-05-06T17:01:28.934282151+08:00","level":"INFO","msg":"stream: started","id":"9xovxj44"}
{"time":"2025-05-06T17:01:28.934441727+08:00","level":"INFO","msg":"writer: Do: started","stream_id":"9xovxj44"}
{"time":"2025-05-06T17:01:28.934645008+08:00","level":"INFO","msg":"handler: started","stream_id":"9xovxj44"}
{"time":"2025-05-06T17:01:28.934782494+08:00","level":"INFO","msg":"sender: started","stream_id":"9xovxj44"}
{"time":"2025-05-06T17:01:28.93676047+08:00","level":"INFO","msg":"stream: closing","id":"9xovxj44"}
{"time":"2025-05-06T17:01:28.966479889+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:01:31.198469005+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:01:35.429523035+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:01:44.410992363+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:02:03.92239906+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:02:38.761387452+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:03:38.790661671+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:04:38.85510035+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:05:38.884123509+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:06:38.946840058+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:07:38.976903718+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:08:39.010413201+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:09:39.039713106+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:10:39.070045932+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:11:28.938189654+08:00","level":"WARN","msg":"sender: taking a long time","seconds":600.000480826,"work":"WorkRecord(*service_go_proto.Record_Run); Control(mailbox_slot:\"r92y5btkmokc\" always_send:true connection_id:\"127.0.0.1:37258\")"}
{"time":"2025-05-06T17:11:39.099109134+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:12:39.149023601+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:13:39.182485842+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:14:39.24714064+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:15:39.27605269+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:16:39.305091201+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:17:39.334874764+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:17:39.335520282+08:00","level":"ERROR","msg":"sender: upsertRun:","error":"failed to upsert bucket: api: failed sending: POST https://api.wandb.ai/graphql giving up after 21 attempt(s): Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:17:39.335775287+08:00","level":"ERROR","msg":"sender: upsertConfig: RunRecord is nil"}
{"time":"2025-05-06T17:17:39.335962731+08:00","level":"INFO","msg":"sender: succeeded after taking longer than expected","seconds":970.398392967,"work":"WorkRecord(*service_go_proto.Record_Run); Control(mailbox_slot:\"r92y5btkmokc\" always_send:true connection_id:\"127.0.0.1:37258\")"}
{"time":"2025-05-06T17:17:39.42388954+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:17:41.546729985+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:17:45.821842896+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:17:54.43462875+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:18:11.42674871+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:18:45.702002275+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:19:45.732128029+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:20:45.761481925+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:21:45.790922713+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:22:45.823991723+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:23:45.85247945+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:24:45.882324586+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:25:45.912211386+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:26:45.945310897+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:27:46.00790337+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:28:46.038134989+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:29:46.067745491+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:30:46.097179243+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:31:46.126795872+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:32:46.172403007+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:33:46.232662467+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:33:46.232825378+08:00","level":"ERROR","msg":"runfiles: CreateRunFiles returned error: api: failed sending: POST https://api.wandb.ai/graphql giving up after 21 attempt(s): Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connect: connection refused"}
{"time":"2025-05-06T17:33:46.234063262+08:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-05-06T17:33:46.234195638+08:00","level":"INFO","msg":"handler: closed","stream_id":"9xovxj44"}
{"time":"2025-05-06T17:33:46.234231628+08:00","level":"INFO","msg":"writer: Close: closed","stream_id":"9xovxj44"}
{"time":"2025-05-06T17:33:46.234254731+08:00","level":"INFO","msg":"sender: closed","stream_id":"9xovxj44"}
{"time":"2025-05-06T17:33:46.234362534+08:00","level":"INFO","msg":"stream: closed","id":"9xovxj44"}
